# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fastrun < Formula
  desc "Command launcher tool for developers"
  homepage "https://github.com/katoken03/fastrun"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/katoken03/fastrun/releases/download/v0.1.0/fastrun_Darwin_x86_64.tar.gz"
      sha256 "945f4cd633b44b2e76c9df5fe545c0d66e63a567e956598f71e7af65db2e7f00"

      def install
        system "go", "build", *std_go_args(output: bin/"f")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/katoken03/fastrun/releases/download/v0.1.0/fastrun_Darwin_arm64.tar.gz"
      sha256 "a4b7ffc8f1a95ce74baa0240ad49bed06305c97d9b1ff74a75b4aac46db34620"

      def install
        system "go", "build", *std_go_args(output: bin/"f")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/katoken03/fastrun/releases/download/v0.1.0/fastrun_Linux_x86_64.tar.gz"
        sha256 "d36b12de8010df522ed41ed3d3e6e31e1f6a0ea53f021294ee4224d3752baa49"

        def install
          system "go", "build", *std_go_args(output: bin/"f")
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/katoken03/fastrun/releases/download/v0.1.0/fastrun_Linux_arm64.tar.gz"
        sha256 "3243e8c54daca5246a3f446fa9b906f74b63c22651b81cd36aca45ce6124f8d7"

        def install
          system "go", "build", *std_go_args(output: bin/"f")
        end
      end
    end
  end

  test do
    system "#{bin}/f --version"
  end
end
