# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fastrun < Formula
  desc "Command launcher tool for developers"
  homepage "https://github.com/katoken03/fastrun"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/katoken03/fastrun/releases/download/v0.1.0/fastrun_Darwin_x86_64.tar.gz"
      sha256 "383976181e8eb0798e89d034314d5e9c1ab50760605dd8e4d9258584dceb196a"

      def install
        system "go", "build", *std_go_args(output: bin/"f")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/katoken03/fastrun/releases/download/v0.1.0/fastrun_Darwin_arm64.tar.gz"
      sha256 "b2d05d712f82a59656d481fd7386f72b9eabb05d7a202dd2a8289c6fe107070e"

      def install
        system "go", "build", *std_go_args(output: bin/"f")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/katoken03/fastrun/releases/download/v0.1.0/fastrun_Linux_x86_64.tar.gz"
        sha256 "04e614d596f07557bd31578e103e0332561ace10ebb1e7626f9feb6da07e70fd"

        def install
          system "go", "build", *std_go_args(output: bin/"f")
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/katoken03/fastrun/releases/download/v0.1.0/fastrun_Linux_arm64.tar.gz"
        sha256 "d290a61feb1ddc58c128236e8a3f15030c5e34088b9922ffafc0a3b8f0318f9f"

        def install
          system "go", "build", *std_go_args(output: bin/"f")
        end
      end
    end
  end

  test do
    system "#{bin}/f --version"
  end
end
