# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fastrun < Formula
  desc "Command launcher tool for developers"
  homepage "https://github.com/katoken03/fastrun"
  version "1.0.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/katoken03/fastrun/releases/download/v1.0.5/fastrun_Darwin_x86_64.tar.gz"
      sha256 "e1bea589113b2258fa9573fde97d8eb86b7e0f01f5f8d099bec5a94b56f2ca24"

      def install
        bin.install "f"
      end
    end
    on_arm do
      url "https://github.com/katoken03/fastrun/releases/download/v1.0.5/fastrun_Darwin_arm64.tar.gz"
      sha256 "1e04da6cc83e5eea3d26b90b08ad9b4f66202342690b3c9093c89c4bf414a559"

      def install
        bin.install "f"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/katoken03/fastrun/releases/download/v1.0.5/fastrun_Linux_x86_64.tar.gz"
        sha256 "7f82b3507a19b4859f03b7145deb9f7eec29d783a04a618b3e4601ba285936ff"

        def install
          bin.install "f"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/katoken03/fastrun/releases/download/v1.0.5/fastrun_Linux_arm64.tar.gz"
        sha256 "3a8abbc1b86eec3a65a3c0d188e7539ea2a1c8a5ab8b3ea6dcaa931ac7bdc2e4"

        def install
          bin.install "f"
        end
      end
    end
  end

  test do
    assert_match "fastrun version", shell_output("#{bin}/f --version")
  end
end
