# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fastrun < Formula
  desc "Command launcher tool for developers"
  homepage "https://github.com/katoken03/fastrun"
  version "1.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/katoken03/fastrun/releases/download/v1.0.3/fastrun_Darwin_x86_64.tar.gz"
      sha256 "2d6610d5f49a7721eeb54dba948cbb47cab1919ebc4c76ca1db9117782625ee7"

      def install
        bin.install "f"
      end
    end
    on_arm do
      url "https://github.com/katoken03/fastrun/releases/download/v1.0.3/fastrun_Darwin_arm64.tar.gz"
      sha256 "1e269eab5e76eae9202e2054cc68b2885352afdb6262f2cfde5dca8a6d976a86"

      def install
        bin.install "f"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/katoken03/fastrun/releases/download/v1.0.3/fastrun_Linux_x86_64.tar.gz"
        sha256 "fcc3bce3b66631ef6c31676b57be00665f371b86d983d722bbf5debd756402ef"

        def install
          bin.install "f"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/katoken03/fastrun/releases/download/v1.0.3/fastrun_Linux_arm64.tar.gz"
        sha256 "e02e021c5f5a2a2064f907a5390b72c279363ee85a4802f7acd02fcd3eb47a48"

        def install
          bin.install "f"
        end
      end
    end
  end

  test do
    assert_match "fastrun version", shell_output("#{bin}/f --version")
  end
end
