# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fastrun < Formula
  desc "Command launcher tool for developers"
  homepage "https://github.com/katoken03/fastrun"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/katoken03/fastrun/releases/download/v1.0.1/fastrun_Darwin_x86_64.tar.gz"
      sha256 "ab90a99bf6344abbb961daac5b71ab40b7d18c5f7d4eaa4bb24bddc6f01fdb19"

      def install
        bin.install "f"
      end
    end
    on_arm do
      url "https://github.com/katoken03/fastrun/releases/download/v1.0.1/fastrun_Darwin_arm64.tar.gz"
      sha256 "1a0dc2a2151049169a9428f2c42ae702f05287b012db697e1cd88f6697cdc234"

      def install
        bin.install "f"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/katoken03/fastrun/releases/download/v1.0.1/fastrun_Linux_x86_64.tar.gz"
        sha256 "4cb5487c60392039c5ec4d32bb450f3e35224fdcd377fef634b8eea34c13f4f9"

        def install
          bin.install "f"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/katoken03/fastrun/releases/download/v1.0.1/fastrun_Linux_arm64.tar.gz"
        sha256 "db019efdcfac27afcc56986831dd55596cb266991d7915f476487295aafa31bc"

        def install
          bin.install "f"
        end
      end
    end
  end

  test do
    assert_match "fastrun version", shell_output("#{bin}/f --version")
  end
end
